production: true

hello:
  world: "Hello, I'm a property"

doctrine:
  orm:
    driver: pdo_sqlite
    scanPaths:
      - 'src/Model/Entity'
    sqlite:
      path: 'db/db.sqlite'

logging:
  name: exampleUsage
  fileHandler:
    path: logs/app.log
    level: DEBUG